### ISSUE TITLE
Crashes with mod The Betweenlands

### ISSUE THREAD

**Issue by victorguima** [Red-Studio-Ragnarok/Alfheim#16]
Game immediately crashes when loading up minecraft 1.12.2, on forge v14.23.5.2859, this is the mod list:

TheBetweenlands-3.9.6-universal.jar
Alfheim-1.0.2.jar
!Red-Core-MC-1.7-1.12-0.5-Dev-3.jar

## Specification:

- OS: Windows 10
- CPU: Ryzen 5 5500
- GPU: Radeon RX 5500 XT
- RAM Allocated: 8GB

No crash report is generated by the game.

**Comment by victorguima** [comment]
Crash also happens with Hesperus, but not with the original [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge)

**Comment by hampop** [comment]
did you add [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter)

**Comment by Desoroxxx** [comment]
> did you add [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) to your game

This is very important as you mention using Red Core but not MixinBooter, MixinBooter is absolutly neccessary to run Alfheim

**Comment by victorguima** [comment]
Hmm, I don't remember now, but since I didn't list it, I probably didn't. I'm using the curseforge app, which automatically adds in and enables required dependencies for me, and when I went to test it just now, MixinBooter was enabled. Could it be that you changed something to cause that? Anyway, the game launched with no issues with those three enabled+MixinBooter, thanks for mentioning it.
