### ISSUE TITLE
Crash with Additions mod

### ISSUE THREAD

**Issue by morealess** [Red-Studio-Ragnarok/Alfheim#24]
## Describe the bug

Additions mod allows you to create blocks or items without making a mod yourself, there is a crash / rendering problem with slabs specifically (I haven't tested other block types from the mod). Placing down a slab results in the slab turning black and a 3x3 area around the slab see through, then the game crashes. Or the screen instantly goes white and crashes.

***A clear and concise description of what the bug is.***

> Remember that a great explanation leads to a greater understanding

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Create a custom slab with the Additions mod
2. Load minecraft with these 5 mods: mixinbooter, redcore, alfheim, additions, lootoverhaul
3. Place slab

## Expected behavior

***A clear and concise description of what you expected to happen.***
The slab should render properly, I tested with original phosphor and it works like normal. This problem only happens with Alfheim installed.

## Screenshots or/and videos

***If applicable, add screenshots and/or videos to help explain your problem.***

## Logs or/and crash reports

***Please use https://mclo.gs/ to upload your logs and crash reports***

https://mclo.gs/feJPh1O

## Versions

- !mixinbooter-8.6
- !Red-Core-MC-1.7-1.12-0.5.1
- Alfheim-1.1.1
- Additions-0.5.2
- LootOverhaul-1.2
- Forge: 1.12.2 - 14.23.5.2859
- Java: JDK 8 - 351
- Java JVM: ?

## Specification:

- OS: Windows 10
- CPU: Ryzen 5 3600
- GPU: Geforce GTX 1050
- RAM Allocated: 8 GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [e.g. 3.80GHz Boost around 4.25Ghz]
- CPU Core: [e.g. 8 (Attention Core not logical core)]
- CPU Threads: [e.g. 16 (Named Logical processors in task manager)]
- RAM Size: [e.g. 32GB]
- RAM Speed: [e.g. 2666MHz]
- Storage Type: [HDD or SSD]
- GPU VRAM: [e.g. 2GB]

> Most of these information can be found in the task manager

## Additional context

***Add any other context about the problem here.***

**Comment by Desoroxxx** [comment]
It is an issue on their side, can you give me a link to the mod on CurseForge/Modrinth/GitHub?

**Comment by morealess** [comment]
https://www.curseforge.com/minecraft/mc-mods/additions-mod hoping for the best

**Comment by Desoroxxx** [comment]
> https://www.curseforge.com/minecraft/mc-mods/additions-mod hoping for the best

Yeah that mod is closed source I can't even propose a fix for them, I would recomend you to just use MCreator for this
