### ISSUE TITLE
Crash with GTCEu when create a new world.

### ISSUE THREAD

**Issue by Death-hao** [Red-Studio-Ragnarok/Alfheim#36]
### Describe the bug

The game will crash when create the world with some seeds(for example: 1271878342426792493).

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/paClmUE

### Crash Reports

https://mclo.gs/uwTAx7u

### Alfheim Version

1.2

### Forge Version

1.12.2-14.23.5.2680

### MixinBooter Version

8.9

### Java Version

1.8-051

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

AMD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Oganesson897** [comment]
I encountered the same error while testing with Cleanroom, the message given in the log indicated that its a problem from some mod that modifies the world, then I removed RTG and BOP it works fine.
I also installed GregTech CEu 2.6.x (latest), but it is okay.

**Comment by Death-hao** [comment]
> I encountered the same error while testing with Cleanroom, the message given in the log indicated that its a problem from some mod that modifies the world, then I removed RTG and BOP it works fine. I also installed GregTech CEu 2.6.x (latest), but it is okay.
However there is no RTG or BOP,I reproduced this issue with as few other mods as possible installed.

**Comment by Desoroxxx** [comment]
Could you try with this version: https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/5201011

**Comment by hampop** [comment]
seems to be fix i was able to create a world with the seed 1271878342426792493 with GTCEu

**Comment by Desoroxxx** [comment]
Amazing
