### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by nveXyounes** [Red-Studio-Ragnarok/Alfheim#38]
### Describe the bug

Minecraft version 1.12.2 with Forge version 1.12.2 - 14.23.5.2860 crashes upon attempting to run the game after adding the Alfheim-1.2.jar mod.

list of mods i'm using : 

additional_lights-1.12.2-1.2.1.2-optional.jar
AdvancementPlaques-1.12.2-1.4.10.jar
aether-1.12.2-v1.5.3.2.jar
Alfheim-1.2.jar
AmbientSounds_v3.1.7_mc1.12.2.jar
animania-1.12.2-base-2.0.3.28.jar
animania-1.12.2-extra-1.0.2.28.jar
animania-1.12.2-farm-1.0.2.28.jar
AquaAcrobatics-1.15.2.jar
Atum-1.12.2-2.0.20.jar
AutoRegLib-1.3-32.jar
BackTools-1.12.2-7.0.1.jar
bettercaves-1.12.2-2.0.4.jar
BetterFps-1.4.8.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
betternether-0.1.8.5.jar
Biome_Bundle_O_Plenty-1.12.2_v1.0.jar
BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
camouflagedcreepers-1.7.1.jar
carryon-1.12.2-1.12.6.20.jar
ChunkAnimator-1.12.2-1.2.1.jar
Clumps-3.1.2.jar
collective-1.12.2-3.0.jar
CoralReef-2.5-1.12.2.jar
coroutil-1.12.1-1.2.37.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CreativeCore_v1.10.70_mc1.12.2.jar
CreepyPastaCraft_Reborn_V2c-1.12.2-hotfix1.jar
davincisvessels-1.12-6.340-full.jar
DivineRPG-1.7.1.jar
DynamicSurroundings-1.12.2-3.6.3.jar
DynamicTrees-1.12.2-0.9.29.jar
DynamicTreesAtum-1.12.2-1.0.4.jar
DynamicTreesBOP-1.12.2-1.5.2.jar
ElectroblobsWizardry-4.3.9.jar
EnchantmentDescriptions-1.12.2-1.1.15.jar
end_spectre-1.0.jar
EnhancedVisuals_v1.4.4_mc1.12.2.jar
EpicSiegeMod-13.168.jar
EyesInTheDarkness-0.1.0.jar
FamiliarFauna-1.12.2-1.0.11.jar
fancylamps-1.2.1.jar
farsight-1.6.jar
FastFurnace-1.12.2-1.3.1.jar
Fish's+Undead+Rising-1.3.2.jar
foamfix-0.10.15-1.12.2.jar
FpsReducer-mc1.12.2-1.20.jar
getittogetherdrops-1.12.2-v1.0.2.jar
gravestone-1.10.3.jar
HMM16.2.1MC1.12.2.jar
Horror_elements_mod_1.5.2_1.12.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
iChunUtil-1.12.2-7.2.2.jar
jei_1.12.2-4.16.1.302.jar
llibrary-1.7.20-1.12.2.jar
mahoutsukai-1.12.2-v1.19.55 16.22.35.jar
mcw-bridges-1.0.6b-mc1.12.2.jar
mcw-fences-1.0.0-mc1.12.2.jar
MobDismemberment-1.12.2-7.0.0.jar
MoBends_1.12.2-1.2.1-19.12.21.jar
movingworld-1.12-6.353-full.jar
mowziesmobs-1.5.8.jar
MutantBeasts-1.12.2-1.0.2.jar
Neat+1.4-17.jar
Nutrition-1.12.2-4.9.0.jar
OpenTerrainGenerator-1.12.2-v9.5-R1.jar
OptiFine_1.12.2_HD_U_G5.jar
OreLib-1.12.2-3.6.0.1.jar
Passive+Aggression-1.12.2-0.0.1.jar
performant-1.11.jar
Quark-r1.6-179.jar
RealisticTorches-1.12.2-2.1.2.jar
RenderLib-1.12.2-1.3.3.jar
savemystronghold-1.12.2-1.0.0.jar
SereneSeasons-1.12.2-1.2.18-universal.jar
SereneTweaks-1.0.jar
SnowRealMagic-1.12.2-0.7.1.jar
SpartanShields-1.12.2-1.5.5.jar
SRParasites-1.12.2v1.9.12.jar
starterkit_1.12.2-2.4.jar
stygian-1.0.4.jar
TenshiLib-1.12.2-1.2.4.jar
TheBetweenlands-3.9.6-universal.jar
tlskincape_1.12.2-1.4.jar
ToughAsNails-1.12.2-3.1.0.141-universal.jar
TravelersBackpack-1.12.2-1.0.35.jar
VanillaFix-1.0.10-150.jar
Waystones_1.12.2-4.1.0.jar
weather2-1.12.1-2.6.12.jar
Xaeros_Minimap_23.9.7_Forge_1.12.jar
XaerosWorldMap_1.37.8_Forge_1.12.jar
zombieawareness-1.12.1-1.11.16.jar
Weather2Remastered-1.12.2-2.8.11.jar.dis

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/uCGF2Nl

### Alfheim Version

1.2

### Forge Version

1.12.2 - 14.23.5.2860

### MixinBooter Version

idk

### Java Version

20

### Java Virtual Machine

Hotspot

### Operating System

mac os 

### GPU Vendor

Intel

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
You are missing [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) and [Red Core](https://www.curseforge.com/minecraft/mc-mods/red-core)
