### ISSUE TITLE
Crash when taking liquid out of an EnderIO portable tank with a bucket

### ISSUE THREAD

**Issue by lynxx131** [Red-Studio-Ragnarok/Alfheim#42]
### Describe the bug

After updating to Alfheim 1.2, I experience crashes when taking fluid out of an EnderIO portable tank or when destroying the tank in creative mode.

I have included a crash report and logs, reverting the mod to 1.1.1 seems to solve the issue, the pack I am testing in is Nomifactory CEU nightly build.

I haven't been able to re-produce the issue in Nomi CEU singleplayer however it can be reliably re-produced in multiplayer.

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [X] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/OorgjKi

### Debug Logs

https://mclo.gs/d0uDa1p

### Crash Reports

https://mclo.gs/LFzx62w

### Alfheim Version

1.2

### Forge Version

1.12.2 - 14.23.5.2860

### MixinBooter Version

9.1

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Fixed in Alfheim 1.3
