### ISSUE TITLE
Game crashes when placing the GregTech Basic Macerator

### ISSUE THREAD

**Issue by crzyblue** [Red-Studio-Ragnarok/Alfheim#43]
### Describe the bug

Game crashes when placing the GregTech Basic Macerator. Checking the crash log, it's trying to set the light level to -1 which is invalid, and causing continuous crash.

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/jGUzXns

### Crash Reports

https://mclo.gs/jGUzXns

### Alfheim Version

1.2

### Forge Version

14.23.5.2859

### MixinBooter Version

8.8

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

Windows 10

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Souliboi** [comment]
It should be noted that in this case the latest version of GregTech Community Edition unofficial was used.

**Comment by Desoroxxx** [comment]
Could you try with this version: https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/5201011

**Comment by Desoroxxx** [comment]
Fixed in Alfheim 1.3
