### ISSUE TITLE
Missing dependancies (curseforge,modrinth,readme)

### ISSUE THREAD

**Issue by Talandar99** [Red-Studio-Ragnarok/Alfheim#45]
### Description

I was trying to run the mod but it was keep failing because of missing red core and mixinbooster

i have managed to figure this out by googling, but updating curseforge page, readme and modrinth page with dependancies would be usefull.

### Screen from curseforge
![image](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/32677600/91b5129b-e552-4b85-bdc9-0604c540e742)

**Comment by Desoroxxx** [comment]
This is a bug with CurseForge, Modrinth has the dependencies correctly set and visible. I hope they fix it soon
