### ISSUE TITLE
Crashes right after start

### ISSUE THREAD

**Issue by youngdrose** [Red-Studio-Ragnarok/Alfheim#47]
### Describe the bug

After i try to start it it instantly crashes, i use it on a big modpack but i only use optimalization from Opticraft page.
https://red-studio-ragnarok.github.io/Opticraft/
Tried it with 1/4 of the mods and still doesnt work.
Anyone know any usual incompatibilities or known popular mods that dont work with Alfheim?

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/gwm4OoL

### Alfheim Version

all

### Forge Version

14.23.5.2854

### MixinBooter Version

9.1

### Java Version

1.8.0 411 

### Java Virtual Machine

Hotspot

### Operating System

Windows 11 

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Those aren't actually logs
