### ISSUE TITLE
Issue: Doesn't launch with FermiumBooter and FermiumAsm

### ISSUE THREAD

**Issue by Desenrrollado** [Red-Studio-Ragnarok/Alfheim#49]
### Describe the bug

It's simple it just doesn't launch with the following mods. I understand if there isn't any support. Though it would be nice to know if it's just because of the differences in the mixinbooter forks. Which I assume this may conflict with.

[FermiumBooter](https://www.curseforge.com/minecraft/mc-mods/fermiumbooter)
[FermiumAsm](https://www.curseforge.com/minecraft/mc-mods/fermiumasm)

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/yB6zls9

### Alfheim Version

1.3

### Forge Version

1.12.2 - 14.23.5.2860

### MixinBooter Version

FerniumBooter 1.1.0

### Java Version

1.8.0_51

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Can't do anything about that

**Comment by jchung01** [comment]
FermiumBooter isn't a replacement for MixinBooter for mods that require it (which Alfheim does). In fact, FermiumBooter isn't even a fork. It should work if you also add MixinBooter.

**Comment by Desenrrollado** [comment]
I've indeed tried that before. It doesn't launch. I'm pretty in-depth with my trouble shooting and testing. In fact I have a bunch of mods that refuse to work in a folder that are as a result of needing Mixinbooter specifically and Censoredasm.

 Here's my log to demonstrate that I have tried. Just including the lighting engine, FermiumBooter, Fermiumasm, and Mixinbooter.
 
[latest.log](https://github.com/user-attachments/files/15527759/latest.log)
![Screenshot_1](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/92115460/bfb03b0c-b0ad-4c3d-99d6-8e0314230948)

I know FermiumASM is a fork of Normalasm/CensoredAsm. Which yeah I can switch the versions and have everything working. If I just use CensoredAsm and Mixinbooter

Though it was more of a curiosity. I had asked similar way back from ACGaming with Universal tweaks. Though it was the same issue. They're just built off different versions with no current compatibility. Which is fine. I just like testing things here and there and comparing them. 
 
I do however appreciate the response and the effort to address this from both of you. If anything sorry to bother and inconvenience you.

**Comment by jchung01** [comment]
> I've indeed tried that before. It doesn't launch. I'm pretty in-depth with my trouble shooting and testing. In fact I have a bunch of mods that refuse to work in a folder that are as a result of needing Mixinbooter specifically and Censoredasm.
> 
> Here's my log to demonstrate that I have tried. Just including the lighting engine, FermiumBooter, Fermiumasm, and Mixinbooter.
> 
> [latest.log](https://github.com/user-attachments/files/15527759/latest.log) ![Screenshot_1](https://private-user-images.githubusercontent.com/92115460/335914213-bfb03b0c-b0ad-4c3d-99d6-8e0314230948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTc2NTEsIm5iZiI6MTcxNzM5NzM1MSwicGF0aCI6Ii85MjExNTQ2MC8zMzU5MTQyMTMtYmZiMDNiMGMtYjBhZC00YzNkLTk5ZDYtOGUwMzE0MjMwOTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA2NDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMWI1NjViMGJhODg3NTQ5ZjY2NWYxNTUwMTgwMTY0OTczMTkyMTA5ZGUwMTFkZDdjZWE0NGI1YWFjYjJlMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YQInFwFxDun4hb4tKjfFh1XZK24FGMuZ520-yeJMxuk)
> 
> I know FermiumASM is a fork of Normalasm/CensoredAsm. Which yeah I can switch the versions and have everything working. If I just use CensoredAsm and Mixinbooter normally. Anything crossing Fermium's ver. and each of those mods is a no go with a similar error.
> 
> Though it was more of a curiosity. I had asked similar way back from ACGaming with Universal tweaks. Though it was the same issue. They're just built off different versions with no current compatibility. Which is fine. I just like testing things here and there and comparing them.
> 
> I do however appreciate the response and the effort to address this from both of you. If anything sorry to bother and inconvenience you.

This crash is only because you don't have RedCore installed, different from your first one. Alfheim + MixinBooter + Red Core + FermiumBooter + FermiumAsm or CensoredAsm launches fine for me.

**Comment by Desenrrollado** [comment]
That's what I blanked on lol. I'll give it a spin later. Well I'm glad that's something I can fix easily later. No idea how I let that slip through when I usually read logs decently. 

Thanks I appreciate it and sorry for my tom foolery. I have a few other mods to look through as well now then. I'm glad it was just that.

Now if only you could take a look at why my modern mc instance causes the player to not exist in the nether after a few min in 1.20.1 . Though that's for another post, mod platform and set of mods entirely lol.

I'll have to recheck those just to make sure I didn't miss another library. It means a lot to me that people like you still help out dorks like me who go back in fourth. 

Have a good rest of your day or, evening or night!
