### ISSUE TITLE
Crash with Nothirium when entering a world

### ISSUE THREAD

**Issue by hampop** [Red-Studio-Ragnarok/Alfheim#5]
## Describe the bug

***A clear and concise description of what the bug is.***

when you enter a world with nothirium  it crash

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Go to 'go in a world with nothirith and it will crash'

## Expected behavior

***A clear and concise description of what you expected to happen.***

not crash when you enter a world with nothirium  

## Screenshots or/and videos 
https://github.com/Red-Studio-Ragnarok/Alfheim/assets/87606666/b50fc3c1-8372-403e-98c8-f2cc6400efe1

## Logs or/and crash reports

[latest.log](https://github.com/Red-Studio-Ragnarok/Alfheim/files/12559849/latest.log)

## Versions

![image](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/87606666/55f8085e-acef-4eed-a9c9-8e30fe1efe85)

## Specification:

- OS: [Windows 11]
- CPU: [Ryzen 5 5500u]
- GPU: [vega 7]
- RAM Allocated: [4gb]

**Comment by Desoroxxx** [comment]
Please remove Mixin Compat it is useless with Mixin Booter, best case scenario it does nothing worst case scenario it causes issues

**Comment by hampop** [comment]
it is the same without Mixin Compat

**Comment by Desoroxxx** [comment]
Try with:
- Only Alfheim (And MixinBooter plus Red Core obviously)
- Only Alfheim (And MixinBooter plus Red Core obviously) and RenderLib

**Comment by hampop** [comment]
it works fine with RenderLib and Entity Culling

**Comment by Desoroxxx** [comment]
Could you try with [1.0.1](https://legacy.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/4743985)

**Comment by hampop** [comment]
ok in 5 mins

**Comment by hampop** [comment]
https://mclo.gs/DM2fkP5  
[latest.log](https://github.com/Red-Studio-Ragnarok/Alfheim/files/12561830/latest.log)

**Comment by Desoroxxx** [comment]
*For future reference:*
![image](https://github.com/Red-Studio-Ragnarok/Alfheim/assets/82710983/d54d7003-1f0c-404f-99f9-327a4a0af9f3)

**Comment by Desoroxxx** [comment]
Fixed in 1.0.2:

[CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/4749295)
[Modrinth](https://modrinth.com/mod/alfheim/version/1.0.2)
