### ISSUE TITLE
Loding OutOfMemoryError

### ISSUE THREAD

**Issue by tier940** [Red-Studio-Ragnarok/Alfheim#51]
### Describe the bug

* Start with a maximum memory of 1024 MiB.

> I am reporting here because it happens with Alfheim Lighting Engine, although it is listed as HEI.
When I unplug Alfheim, it never crashes with OutOfMemoryError, and when I introduce it, it errors starting up.
> Incidentally, I started to use it as a changeover from 燐/Hesperus.

[1.12.2-outmem.zip](https://github.com/user-attachments/files/16060604/1.12.2-outmem.zip)

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/biGPeks

### Alfheim Version

1.3

### Forge Version

14.23.5.2860

### MixinBooter Version

9.1

### Java Version

1.8.0_412

### Java Virtual Machine

Hotspot

### Operating System

ArchLinux & Windwos11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MCTian-mi** [comment]
probably due to #46, fixed in GregTechCEu/GregTech#2475
