### ISSUE TITLE
"requires MixinBooter 8.8 (or above)" Despite having mixinbooter.

### ISSUE THREAD

**Issue by TanksNBoats** [Red-Studio-Ragnarok/Alfheim#59]
### Describe the bug

As the title says, the logs and crash message say "mixinbooter 8.8" is missing, when it isn't, I try downgrading from 9.3 > 8.8 to see if it would work and nope. I try removing the "!" before mixinbooter and that just crashes, no matter what I do and what mods I remove it still says that mixinbooter is missing

![image](https://github.com/user-attachments/assets/ba26f412-4bfd-49a8-a1a2-11d8883a2f8e)
![image](https://github.com/user-attachments/assets/cf7b0c02-f3f9-443f-bb3f-37c18990ff01)

### Reproducibility

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/gTdZh5s#L1942

### Crash Reports

No log found

### Alfheim Version

1.4

### Forge Version

1.12.2 - 14.23.5.2860

### MixinBooter Version

8.9

### Java Version

1.8

### Java Virtual Machine

Hotspot

### Operating System

Windows 11

### GPU Vendor

NVIDIA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Desoroxxx** [comment]
Could you try re-downloading MixinBooter from CurseForge

**Comment by beltxd** [comment]
If you have Essentials, remove it.

**Comment by Desoroxxx** [comment]
Oh yeah, afaik it's an issue with Essentials

**Comment by Desoroxxx** [comment]
Reopen if it wasn't Essentials
