### ISSUE TITLE
`alfheim.utils.DeduplicatedLongQueue.clearSet()` drop FPS to `20`

### ISSUE THREAD

**Issue by Krutoy242** [Red-Studio-Ragnarok/Alfheim#69]
### Describe the bug

Happens in E2EE modpack. I opened my old world and on my base I can see only 20 FPS.
When I profiled it with `/sparkc profiler` it pointed on Alfheim:
![image](https://github.com/user-attachments/assets/6b63d405-9d6a-46f4-b1e6-25339a01b766)

## https://spark.lucko.me/BSzphEggnH?hl=71

I dont know what block / mechanism / entity is causing this. Would be glad to get help on investigating.

I cannot stably reproduce this issue - rejoining this world again fix FPS back to normal.

Its a skyblock btw 
![image](https://github.com/user-attachments/assets/d57d62be-af62-4a15-b6de-225687eb3e4f)

### Reproducibility

- [ ] I reproduced this issue with as few other mods as possible installed.
- [X] I am unable to reproduce this issue consistently.

### Logs

https://mclo.gs/usbZfGz

- Alfheim 1.4
- Forge 2860
- MixinBooter 9.4
- Java 23.0.1
- OS Win 10
- GPU NVIDIA

**Comment by Desoroxxx** [comment]
I will push a dev build soon trying to address this

**Comment by Desoroxxx** [comment]
Could you try again with [the new dev build](https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/5904015)?

**Comment by Krutoy242** [comment]
> Could you try again with [the new dev build](https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/5904015)?

I cannot stably reproduce the issue on old version.
I tried to log in after game loading. Tried to stay in world for an hour. Tried to fly around - nothing reproduce this FPS drop. So, even if i would install new version, how it could be useful?

**Comment by Desoroxxx** [comment]
I am pretty sure this is fixed, if it isn't please reopen this issue
