### ISSUE TITLE
Crash on startup on Mohist server

### ISSUE THREAD

**Issue by FranklinMCA** [Red-Studio-Ragnarok/Alfheim#8]
## Describe the bug

***Crash on startup on Mohist server***

> Remember that a great explanation leads to a greater understanding

## Reproducibility
Every depencies correctly installed on server, but when it starts just crash inmediately.

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

## Expected behavior

***A clear and concise description of what you expected to happen.***

## Screenshots or/and videos

***If applicable, add screenshots and/or videos to help explain your problem.***

## Logs or/and crash reports

***https://mclo.gs/KbZ4cvs***

## Versions

- Mohist-1.12.2-342
- Forge: 1.12.2 - 14.23.5.2860
- Java: JDK 8 - 312
- Java JVM: OpenJDK

## Specification:

- OS: Debian 11
- CPU: Intel Core i9 9900K
- GPU: Not present
- RAM Allocated: 8GB

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [e.g. 3.80GHz Boost around 4.25Ghz]
- CPU Core: [e.g. 8 (Attention Core not logical core)]
- CPU Threads: [e.g. 16 (Named Logical processors in task manager)]
- RAM Size: [e.g. 32GB]
- RAM Speed: [e.g. 2666MHz]
- Storage Type: [HDD or SSD]
- GPU VRAM: [e.g. 2GB]

> Most of these information can be found in the task manager

## Additional context

***Add any other context about the problem here.***

**Comment by Desoroxxx** [comment]
Somewhat expected, will make Alfheim disable itself when Mohist is detected next update if no easy fix is possible

**Comment by Desoroxxx** [comment]
> Somewhat expected, will make Alfheim disable itself when Mohist is detected next update if no easy fix is possible

Nevermind that should be fixed in 1.0.2:

[CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/4749295)
[Modrinth](https://modrinth.com/mod/alfheim/version/1.0.2)

**Comment by FranklinMCA** [comment]
It still crashes on server loading: https://mclo.gs/BklC3ZV

**Comment by Desoroxxx** [comment]
> It still crashes on server loading: https://mclo.gs/BklC3ZV

I fixed that can you try with the new dev build?
https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/4838765

**Comment by Fersteax** [comment]
> > It still crashes on server loading: https://mclo.gs/BklC3ZV
> 
> I fixed that can you try with the new dev build? https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine/files/4838765

Yeah, it launches now.

**Comment by Desoroxxx** [comment]
> Yeah, it launches now.

Awesome
